function(version MAJOR MINOR PATCH)
    set (APP_VERSION_MAJOR ${MAJOR} PARENT_SCOPE)
    set (APP_VERSION_MINOR ${MINOR} PARENT_SCOPE)
    set (APP_VERSION_PATCH ${PATCH} PARENT_SCOPE)

    file(WRITE "${PROJECT_SOURCE_DIR}/include/${APP_NAME}/version-def.h" "// Generated by cmake version()
#define APP_VERSION_MAJOR ${MAJOR}
#define APP_VERSION_MINOR ${MINOR}
#define APP_VERSION_PATCH ${PATCH}
constexpr std::string_view getAppVersion() { return \"${MAJOR}.${MINOR}.${PATCH}\"; }
    ")
endfunction()
